[package]
name = "podpacker"
version = "0.1.0"
authors = ["Yohaï-Eliel BERREBY <yberreby@protonmail.ch>"]
edition = "2018"


[dependencies]
serde_json = "1.0.56"
serde_derive = "1.0.114"
serde = { version = "1.0.114", features = ["derive"] }
clap = "2.33.1"

